# Generated by Django 4.2.4 on 2024-02-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipecategory",
            name="description",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
